# Font
font_family IoskeleyMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 16.0

# Window
hide_window_decorations yes
shell /usr/bin/bash
confirm_close no

# Theme
include themes/farout.conf

# Spacing
modify_font cell_height 105%
modify_font cell_width 100%

# Cursor
cursor_shape underline
cursor_blink_interval 0
cursor #D47D49
cursor_text_color #0F0908

# Selection
selection_foreground #0F0908
selection_background #D47D49

# Other
url_color #D47D49
disable_ligatures always
scrollback_lines 10000
tab_bar_edge bottom
tab_bar_style separator

# Font resizing
map ctrl+wheel_up change_font_size all +1.0
map ctrl+wheel_down change_font_size all -1.0
