# Miasma

foreground #C2C2B0
background #222222

selection_foreground #222222
selection_background #C2C2B0

cursor #C2C2B0
cursor_text_color #222222

url_color #78824B

active_border_color #78824B
inactive_border_color #444444
bell_border_color #C94C4C

tab_bar_background #222222
active_tab_foreground #222222
active_tab_background #78824B
inactive_tab_foreground #888888
inactive_tab_background #2D2D2D

color0 #222222
color8 #666666

color1 #C94C4C
color9 #D47F7F

color2 #78824B
color10 #A3A95F

color3 #C9A554
color11 #D7C27C

color4 #5F6F7A
color12 #7F9BA6

color5 #8F6B7A
color13 #B18A9A

color6 #5F8787
color14 #7FAAAA

color7 #C2C2B0
color15 #D0D0BD
